[project]
name = "auto-lumberjack"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "mss>=10.1.0",
    "opencv-python>=4.12.0.88",
    "pynput>=1.8.1",
]
